- app/Models/Complaint.php
- app/Models/Officer.php
- app/Models/Response.php
- app/Models/Student.php
- app/Models/User.php
- resources/views/dashboard/complaints/show.blade.php
Create a response UI in the detail of complaint, fix complaint's sluggable, and fix relations of each model.
> Response UI

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/ComplaintController.php
- app/Http/Controllers/ResponseController.php
- app/Http/Kernel.php
- app/Http/Middleware/ResponseDashboard.php
- database/factories/ResponseFactory.php
- database/migrations/2023_03_01_131400_create_responses_table.php
- resources/js/sweetalert.js
- resources/js/sweetalert/swalMulti.js
- resources/js/sweetalert/swalSingle.js
- resources/views/dashboard/complaints/create.blade.php
- resources/views/dashboard/complaints/edit.blade.php
- resources/views/dashboard/complaints/index.blade.php
- resources/views/dashboard/complaints/show.blade.php
- resources/views/dashboard/responses/create.blade.php
- resources/views/dashboard/responses/edit.blade.php
- resources/views/dashboard/responses/index.blade.php
- resources/views/dashboard/responses/show.blade.php
- routes/web.php
Response with feature create, read, update, and delete.
> feat: response crud

- app/Http/Controllers/DashboardController.php
- database/factories/ComplaintFactory.php
- resources/views/dashboard/complaints/show.blade.php
- resources/views/dashboard/index.blade.php
- resources/views/dashboard/responses/create.blade.php
- resources/views/dashboard/responses/index.blade.php
- routes/web.php
Create a dashboard for user as officers.
> feat: dashboard/response

- app/Http/Controllers/ComplaintController.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/ResponseController.php
- resources/views/dashboard/index.blade.php
- resources/views/dashboard/responses/edit.blade.php
- resources/views/dashboard/responses/show.blade.php
Add authorization to URLs (show and edit).
> feat: authorization

- README.md
fix the headline of application in README.md
> docs: fix headline

- app/Http/Controllers/DashboardController.php
fix dashboard greetings timezone
> fix dashboard timezone

- app/Http/Controllers/DashboardController.php
- app/Models/Complaint.php
- app/Models/Response.php
- database/factories/ComplaintFactory.php
- database/factories/ResponseFactory.php
- database/seeders/DatabaseSeeder.php
- resources/js/dashboard.js
Moved all of logic in controller (DashboardController) to each model (Complaint and Response).
> feat: logics in model

- app/Http/Controllers/DashboardController.php
- app/Services/ChartService.php
- resources/js/dashboard.js
- routes/web.php
Put extra business logic in ChartService and import it into DashboardController.
> feat: ChartService

- app/Http/Controllers/DashboardController.php
- app/Services/Dashboard/DashboardService.php
- resources/js/dashboard.js
- resources/views/dashboard/index.blade.php
Add dashboard student feature.
> feat: dashboard/student

- app/Http/Controllers/ComplaintController.php
Fix amount of excerpt from 200 to 50.
> chore: fix excerpt

- app/Http/Controllers/AdminCategoryController.php
- app/Http/Controllers/ComplaintController.php
- app/Models/Category.php
- database/migrations/2023_03_01_131308_create_complaints_table.php
- resources/js/image.js
- resources/js/sluggable.js
- resources/js/sluggable/slug.js
- resources/js/sweetalert/swalMulti.js
- resources/views/dashboard/categories/create.blade.php
- resources/views/dashboard/categories/edit.blade.php
- resources/views/dashboard/categories/index.blade.php
- resources/views/dashboard/complaints/create.blade.php
- resources/views/dashboard/complaints/edit.blade.php
- resources/views/dashboard/index.blade.php
- routes/web.php
- vite.config.js
> feat: admin category

- resources/css/app.css
- resources/views/dashboard/layouts/sidebar.blade.php
> fix: logo in sidebar dashboard

- resources/views/layouts/footer.blade.php
Fix footer background in light mode.
> fix footer in light mode

- resources/views/dashboard/layouts/footer.blade.php
- resources/views/dashboard/layouts/main.blade.php
Make different footer for dashboard.
> seperating footers home and dashboard

- resources/views/layouts/footer.blade.php
> fix: overflow background in mobile view

- resources/css/app.css
> fix: bug darkmode in home page

- composer.json
- composer.lock
- storage/debugbar/.gitignore
Add Laravel Debugbar: https://github.com/barryvdh/laravel-debugbar
> laravel debugbar

- app/Http/Controllers/ComplaintController.php
- app/Http/Controllers/ResponseController.php
- app/Models/Complaint.php
- app/Models/Officer.php
- app/Models/Response.php
- app/Models/Student.php
- app/Providers/AppServiceProvider.php
- app/Services/Dashboard/DashboardService.php
- config/app.php
- database/seeders/DatabaseSeeder.php
Do eager loadings in each queries.
> eager loadings

- resources/js/dashboard.js
- resources/views/dashboard/index.blade.php
Add skeleton loadings to all of the charts.
> skeleton loadings

- app/Http/Controllers/ResponseController.php
- resources/js/sweetalert.js
- resources/js/sweetalert/swalMulti.js
- resources/views/dashboard/complaints/show.blade.php
- resources/views/dashboard/index.blade.php
- resources/views/dashboard/responses/create.blade.php
- resources/views/dashboard/responses/index.blade.php
I have improved some UIs in the response section.
1. When a complaint had done, then admin or officer can see the details.
2. When admin or officer do their own response, there are actions (update, detail, delete) for the response.
3. And we have also changed the display when an admin or officer creates a response.
> improvised response UI

- resources/css/app.css
- resources/views/about.blade.php
- resources/views/home.blade.php
fix bug di landing page dan ganti kalimat kalimat di about dan alur melapor
> Fix:landing page

- resources/css/app.css
> fix: bug darkmode in navbar

- resources/css/app.css
> fix: background color home in darkmode

- resources/css/app.css
- resources/js/changepassword.js
- resources/js/showpassword.js
- resources/views/auth/login.blade.php
- resources/views/dashboard/partials/script.blade.php
- resources/views/dashboard/users/password.blade.php
- resources/views/partials/script.blade.php
change password in dashboard
field password in login page
> feat: show password
